/* MTI_DPI */

/*
 * Copyright 2002-2018 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPI
#define INCLUDED_DPI

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
c_add(
    int a,
    int b);

DPI_LINK_DECL DPI_DLLESPEC
void
display();

DPI_LINK_DECL void
display_in_sv();

#endif 
